language: ruby
rvm:
  - 2.1.5
before_install:
  - sudo apt-get update
install:
  - sudo apt-get -y install autoconf
  - sudo apt-get -y install build-essential
  - sudo apt-get -y install devscripts
  - sudo apt-get -y install liburi-perl
  - sudo apt-get -y install libencode-perl
  - sudo apt-get -y install libwww-perl
  - sudo apt-get -y install libhtml-lint-perl
  - sudo apt-get -y install libmagickcore-dev libmagickwand-dev
  - bundle install
  - bundle exec jekyll build
script:
  - make citest
notifications:
  irc:
    channels:
      - "chat.freenode.net#thruk-dev"
    on_success: change
    on_failure: always
    skip_join: true
