name: citest

on:
  push:
  pull_request:
  release:

jobs:
  citest:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      #- name: Setup tmate session, see https://github.com/marketplace/actions/debugging-with-tmate
      #  uses: mxschmitt/action-tmate@v3
      - name: prepare machine
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
            autoconf \
            build-essential \
            devscripts \
            libencode-perl \
            libhtml-lint-perl \
            libmagickcore-dev \
            libmagickwand-dev \
            libreadline-dev \
            liburi-perl \
            libwww-perl \
            nodejs \
            ruby-bundler \
            ruby-dev \
            zlib1g-dev

      - name: run build
        run: |
          make build

      - name: run tests
        run: |
          make citest
